// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://dnldygawqwkubropbkrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRubGR5Z2F3cXdrdWJyb3Bia3J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzI3OTksImV4cCI6MjA3MDE0ODc5OX0.tbX1FHtRMsPdpmCEGp1AhBYGtW2S45o-vRwQzCdkoIU";

// To use the Supabase client - import it as follows:
// import { supabase } from "@/integrations/supabase/client"

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage, 
      persistSession: true, // Ensures session persists across page reloads
      autoRefreshToken: true, // Automatically refreshes token before it expires
    },
  }
);
